<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <AssemblyName>MemWatch</AssemblyName>
    <RootNamespace>MemWatch</RootNamespace>
    <StartupObject>MemWatch.Program</StartupObject>
    <Optimize>true</Optimize>
  </PropertyGroup>
    <ItemGroup>
    <None Include="app.ico" />
    <EmbeddedResource Include="app.ico" LogicalName="MemWatch.app.ico" />
    <Content Include="Assets\Ocean\*.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
    </Content>
  </ItemGroup>

  <!-- 单文件但不自带运行时：依赖电脑已安装 .NET 8 Desktop Runtime -->
  <PropertyGroup Condition="'$(PublishSingleFile)' == 'true'">
    <SelfContained>false</SelfContained>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.4" />
    <PackageReference Include="Open.NAT" Version="2.1.0" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
  </ItemGroup>

</Project>
